version: '3'

services:
 django:
  container_name: django_eatenAway
  image: django:1.0
  environment:
    - DJANGO_DEBUG=true
  volumes:
    - ./code:/code
  ports:
    - "8000:8000"
  tty: true
  command: python3 ./eatenAway/manage.py runserver 0:8000
