# Generated by Django 3.0.3 on 2020-03-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuname', models.CharField(max_length=30, unique=True, verbose_name='메뉴이름')),
                ('category', models.CharField(max_length=30, verbose_name='카테고리')),
                ('country', models.CharField(max_length=30, verbose_name='나라')),
                ('ingredient', models.CharField(max_length=30, null=True, verbose_name='재료')),
                ('taste', models.CharField(max_length=30, verbose_name='맛')),
                ('stock', models.BooleanField(default=False, verbose_name='국물여부')),
                ('description', models.CharField(max_length=50, verbose_name='설명')),
                ('profile', models.ImageField(blank=True, upload_to='food_profile/profile_picture', verbose_name='음식사진')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
            ],
        ),
    ]
