# Generated by Django 3.0.3 on 2020-03-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20200312_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='menuname',
            field=models.CharField(max_length=30, unique=True, verbose_name='메뉴이름'),
        ),
    ]
