# Generated by Django 3.0.3 on 2020-03-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20200312_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='profile',
            field=models.ImageField(blank=True, upload_to='eatenAway/static/images/food_profile/', verbose_name='음식사진'),
        ),
    ]
