# Generated by Django 3.0.3 on 2020-03-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20200313_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUserFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, verbose_name='유저')),
                ('food', models.CharField(max_length=30, verbose_name='메뉴')),
                ('date', models.DateField(verbose_name='날짜')),
            ],
        ),
    ]
