# Generated by Django 3.0.3 on 2020-03-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_dailyuserfood'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyuserfood',
            name='mealkind',
            field=models.CharField(choices=[('B', '아침'), ('L', '점심'), ('D', '저녁')], default='L', max_length=1, verbose_name='식사종류'),
        ),
    ]
