# Generated by Django 3.0.3 on 2020-03-02 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('birth', models.DateField()),
                ('area', models.CharField(max_length=10)),
                ('sex', models.CharField(choices=[('M', '남성'), ('W', '여성')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_no', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=10, verbose_name='ID')),
                ('email', models.EmailField(max_length=32, verbose_name='이메일')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='가입날짜')),
                ('comment', models.CharField(max_length=20, verbose_name='코멘트')),
                ('status', models.CharField(choices=[('O', '정상'), ('X', '삭제'), ('B', '정지')], max_length=1)),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='개인정보')),
            ],
        ),
    ]
