# Generated by Django 3.0.3 on 2020-03-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user_info',
        ),
        migrations.AddField(
            model_name='account',
            name='area',
            field=models.CharField(default='Seoul', max_length=10, verbose_name='지역'),
        ),
        migrations.AddField(
            model_name='account',
            name='birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='Chihiro', max_length=20, verbose_name='이름'),
        ),
        migrations.AddField(
            model_name='account',
            name='sex',
            field=models.CharField(choices=[('M', '남성'), ('W', '여성')], default='W', max_length=1),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
