# Generated by Django 3.0.3 on 2020-03-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200303_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(default=1, max_length=10, verbose_name='아이디'),
            preserve_default=False,
        ),
    ]
