# Generated by Django 3.0.3 on 2020-03-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200304_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('O', '정상'), ('X', '삭제'), ('B', '정지'), ('W', '검증')], max_length=1),
        ),
    ]
