# Generated by Django 3.0.3 on 2020-03-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200305_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(default=1, max_length=16, verbose_name='패스워드'),
            preserve_default=False,
        ),
    ]
