# Generated by Django 3.0.3 on 2020-03-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_account_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='account',
            name='profile',
            field=models.ImageField(blank=True, upload_to='user_profile/profile_picture'),
        ),
        migrations.AlterField(
            model_name='account',
            name='comment',
            field=models.CharField(blank=True, max_length=20, verbose_name='코멘트'),
        ),
    ]
