# Generated by Django 3.0.3 on 2020-03-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200305_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birth',
            field=models.DateField(null=True, verbose_name='생일'),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile',
            field=models.ImageField(blank=True, upload_to='user_profile/profile_picture', verbose_name='프로필'),
        ),
        migrations.AlterField(
            model_name='account',
            name='sex',
            field=models.CharField(choices=[('M', '남성'), ('W', '여성')], default='W', max_length=1, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('O', '정상'), ('X', '삭제'), ('B', '정지'), ('W', '검증')], default='W', max_length=1, verbose_name='계정 상태'),
        ),
    ]
