# Generated by Django 3.0.3 on 2020-03-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200305_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='active',
            field=models.BooleanField(default=False, verbose_name='이메일 인증여부'),
        ),
    ]
